# -*- coding: utf-8 -*-
"""OopFirstProject.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13nQzRN_EXyau7f5aJjtWa5rYEx7BOMY1

**Writing a program of ATM functionality using OOP concept**
"""

class Atm:
  def __init__(self):
    self.pin = ''
    self.balance=0

  def menu(self):
    user_input = input('''
    Hello, how would you like to proceed?
    1. Enter 1 to create pin
    2. Enter 2 to deposit amount
    3. Enter 3 to withdraw amount
    4. Enter 4 to check balance
    5. Enter 5 to exit
    ''')
    if user_input == '1':
      self.create_pin()
    elif user_input == '2':
      self.deposit()
    elif user_input == '3':
      self.withdraw()
    elif user_input == '4':
      self.check_balance()
    else:
      exit()
  def create_pin(self):
    user_pin = input('Enter your pin')
    self.pin = user_pin
    user_balance = int(input('Enter balance'))
    self.balance = user_balance
    print('Pin created successfully')
    self.menu()
  def deposit(self):
    user_pin = input('Enter the pin')
    if user_pin == self.pin:
      amount = int(input('ENter the amount to deposit'))
      self.balance = self.balance + amount
      print('Deposit successful')
    else:
      print('Enter wrong pin')
    self.menu()
  def withdraw(self):
    user_pin = input('Enter the pin')
    if user_pin == self.pin:
      amount = int(input('Enter the amount to withdraw'))
      if amount <= self.balance:
        self.balance = self.balance-amount
        print('Withdrawn successful')
        print('Remaining balance is ',self.balance)
      else:
        print('Insufficient balance')
    else:
      print('Enter wrong pin')
    self.menu()
  def check_balance(self):
    user_pin = input('Enter the pin')
    if user_pin == self.pin:
      print('Your balance is ',self.balance)
    else:
      print('Enter wrong pin')
    self.menu()

obj = Atm()
obj.menu()